version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: my_postgres_db
    restart: unless-stopped
    ports: 
    - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data